### ISSUE TITLE
enter score for student 1; it automatically enters the same score for student 2.

### ISSUE THREAD

**Issue by aanimesh** [peerreviewsystem/peerreviewsystem#4]
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/4524009/64643703-fb126d00-d3de-11e9-8754-daefd01f1e04.png">

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/4524009/64643748-18473b80-d3df-11e9-96b5-dbc4c588c81c.png">

**Comment by peerreviewsystem** [comment]
Fixed.
